---
title: "ANOVA in R"
author: "S. Katie Fogg"
date: "October 22, 2019"
output: pdf_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1-way ANOVA
```{r}
# The data() function loads R default datasets
#   Notice in the environment it says <Promise>: the dataset will truly be loaded as soon as you use it directly in your code
data("InsectSprays")
# the help() function gives information about the specified dataset
help("InsectSprays")
# str() gives information about the dataset
str(InsectSprays)
```

1. Descriptive Statistics
```{r}
# Returns the values in the count column where the spray column is equal to "A"
InsectSprays$count[InsectSprays$spray == "A"]
# Find mean of treatment "A"
mean(InsectSprays$count[InsectSprays$spray == "A"])

# To simplify the above line of code, use the with() function
# The with() function specifies a data environment in which the expession can be evaluated
# In the mean function, we refer directly to the columns within the dataframe. The
#  with() statement specifies which dataframe those columns can be found
with(InsectSprays, mean(count[spray=="A"]))

# This tapply statement can be thought of as:
#   "Apply the function 'mean' to the response variable 'count' for each treatment 'spray'
with(InsectSprays, tapply(count, spray, mean))

# Variance within spray groups
with(InsectSprays, tapply(count, spray, var))

# Length of the data within each group
with(InsectSprays, tapply(count, spray, length))

# Look at the data by creating a boxplot. Note the different arguements that improve plot visualization:
boxplot(count ~ spray,
        data = InsectSprays,
        xlab = "Type of spray",
        ylab = "Insect count",
        main = "InsectSprays data",
        col = "lightgray")

```

## A Couple of Asides:
```{r}
# This created re-ordered factor
# The importnace of releveling becomes apparent when looking at the output table from an ANOVA. Each group is compared to the first group. 
# Say you want to compare the effectiveness of insect sprays to the no spray control, which is spray "F":
spray_relevel <- relevel(InsectSprays$spray, ref = "F")
# releveling within the dataframe is better practice:
InsectSprays$spray <- spray_relevel

# This creates ordered variables where F<B<C<D<E<A
Photoperiod <- ordered(spray, levels = c("F", "B", "C", "D", "E", "A"))

# Check the releveling within the dataframe
with(InsectSprays, tapply(count, spray, mean))

# Check if a variable is a factor using the function is.factor()
is.factor(Photoperiod)

```

2. Run 1-way ANOVA
  a. oneway.test()
```{r}
# read as: "Count is a function of Spray"
oneway.test(count ~ spray)

# Default is equal variances, to account for unequal variances:
oneway.test(count ~ spray, var.equal = FALSE)
```

  b. Run an ANOVA using aov()
```{r}

```

